spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  application:
    name: agents-demo
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          temperature: 0.5 # 模型温度：作用是改变模型输出的随机性，取值范围[0,1]，越小越 deterministic
          max-tokens: 1000 # 模型生成的最大长度
          model: qwen-plus # DashScopeChatModel.DEFAULT_MODEL_NAME
    openai:
      api-key: ${DEEPSEEK_API_KEY} # openai依赖默认自动配置deepseek
      base-url: ${DEEPSEEK_BASE_URL}
      chat:
        options:
          model: deepseek-chat
  main:
    web-application-type: servlet # 指定为Servlet模式


# LLM 提供商配置
llm:
  providers:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: # dashscope的起步依赖不需要配置
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: ${DEEPSEEK_BASE_URL}
    # 后面可以再加入新的LLM模型提供商，再在LlmProperties类和配置类里添加对应模型
